# HW1 - Teodor SIMIC

In [1]:
import numpy as np
import pandas as pd

units = np.array([
    [12, 30, 8, 10],
    [15, 24, 6, 12],
    [10, 35, 9, 8],
    [18, 28, 7, 15],
    [20, 40, 12, 16],
    [16, 32, 10, 14],
])
prices = np.array([1200, 200, 500, 700])

sales = pd.DataFrame({
    "sale_id": np.arange(101, 125),
    "day": [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3,
            4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6],
    "product": ["Notebook", "Pen", "Folder", "Marker"] * 6,
    "category": ["Paper", "Writing", "Paper", "Writing"] * 6,
    "units_sold": units.reshape(-1),
    "unit_price_amd": [1200, 200, 500, 700] * 6,
})

## Part 1 — NumPy foundations (30 points)
### 1.1 Array creation and shape — 5 points
Create the integers 1 through 24 using  np.arrange , then reshape them into a 6 × 4 array called practice,
Display its shape and transpose. Explain why reshaping these 24 values into a 5 × 5 array is impossible; do not leave a failing cell in your submission

In [2]:
A = np.arange(1,25)

In [3]:
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [4]:
practice = A.reshape(6,4)

In [5]:
practice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [6]:
practice.shape

(6, 4)

In [7]:
practice.T

array([[ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23],
       [ 4,  8, 12, 16, 20, 24]])

Reshaping these 24 values into a 5 × 5 array is impossible because reshape cannot add or remove values: the new shape must contain exactly the same number of elements. A 5 × 5 array needs 5 × 5 = 25 elements, but we only have 24, so it leads to an error

###1.2 Indexing and slicing — 7 points
Using units, select and display:
(a) all quantities for Day 3;
(b) Pen quantities across all days;
(c) the final two days and first two products as a 2 * 2 array;
(d) the Marker quantity on the final day using negative indexes.

In [8]:
units

array([[12, 30,  8, 10],
       [15, 24,  6, 12],
       [10, 35,  9,  8],
       [18, 28,  7, 15],
       [20, 40, 12, 16],
       [16, 32, 10, 14]])

In [9]:
units[2]

array([10, 35,  9,  8])

In [10]:
units[:, 1]

array([30, 24, 35, 28, 40, 32])

In [11]:
units[-2:, 0:2]

array([[20, 40],
       [16, 32]])

In [12]:
units[-1, -1]

np.int64(14)

### 1.3 Boolean masks and replacement — 8 points
Extract all values in units that are at least 15 and less than 30 using a Boolean mask.
Then use np.where to create adjusted_units, replacing values below 10 with 0 and keeping all other values.
Display adjusted_units - units.
Explain why & and parentheses are needed when combining the two array conditions.

In [13]:
units[(units >= 15) & (units < 30)]

array([15, 24, 18, 28, 15, 20, 16, 16])

In [14]:
adjusted_units = np.where(units < 10, 0, units)

In [15]:
adjusted_units

array([[12, 30,  0, 10],
       [15, 24,  0, 12],
       [10, 35,  0,  0],
       [18, 28,  0, 15],
       [20, 40, 12, 16],
       [16, 32, 10, 14]])

In [16]:
adjusted_units - units

array([[ 0,  0, -8,  0],
       [ 0,  0, -6,  0],
       [ 0,  0, -9, -8],
       [ 0,  0, -7,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

Why "&": Each comparison like units >= 15 returns an array of booleans, and and raises an error because it can't decide whether a whole array is true or false; & works element-wise, comparing the two arrays position by position.

Why parentheses: Because of operator precedence, "&" is evaluated before the comparisons, so without parentheses Python would try 15 & units first; wrapping each comparison in parentheses forces them to be computed first.

### 1.4 Summary calculations — 10 point
Using the original units, calculate: total units for each day; mean daily units for each product; median units across the four products for each day; and the overall population standard deviation (use np.std with its default settings). Label which result belongs to which day or product. Explain what axis=0 and axis=1 mean for this array.

In [17]:
print("Total units per day :", np.sum(units, axis=1))
print("Mean daily units per product (Notebook, Pen, Folder, Marker):", np.mean(units, axis=0))
print("Median units across the four products per day :", np.median(units, axis=1))
print("Overall population standard deviation:", np.std(units))

Total units per day : [60 57 62 68 88 72]
Mean daily units per product (Notebook, Pen, Folder, Marker): [15.16666667 31.5         8.66666667 12.5       ]
Median units across the four products per day : [11.  13.5  9.5 16.5 18.  15. ]
Overall population standard deviation: 9.387399207921696

### Part 2 — Inspect and transform with pandas (25 points)
### 2.1 Inspect the data — 7 points
Create df = sales.copy(). Display its first five rows, shape, column names, and data types. Show the unique products, the number of unique products, and the number of rows in each category using value_counts. In one sentence, explain what one row represents.

In [18]:
df = sales.copy()
df.head()

   sale_id  day   product category  units_sold  unit_price_amd
0      101    1  Notebook    Paper          12            1200
1      102    1       Pen  Writing          30             200
2      103    1    Folder    Paper           8             500
3      104    1    Marker  Writing          10             700
4      105    2  Notebook    Paper          15            1200

In [19]:
print("Shape:", df.shape)
print("Columns:", list(df.columns))
print("Data types:")
print(df.dtypes)

Shape: (24, 6)
Columns: ['sale_id', 'day', 'product', 'category', 'units_sold', 'unit_price_amd']
Data types:
sale_id            int64
day                int64
product           object
category          object
units_sold         int64
unit_price_amd     int64
dtype: object

In [20]:
print("Unique products:", df["product"].unique())
print("Number of unique products:", df["product"].nunique())
print("Rows per category:")
print(df["category"].value_counts())

Unique products: ['Notebook' 'Pen' 'Folder' 'Marker']
Number of unique products: 4
Rows per category:
category
Paper      12
Writing    12
Name: count, dtype: int64

Every row represents the sales of one product on one day: how many units of that product were sold that day, at which unit price.

### 2.2 Create new columns — 12 points
Add revenue_amd as quantity multiplied by unit price. Add product_label by combining category and product with " - " between them. Use apply with a lambda function to add product_name_length, the character count of each product name. Use np.where to add volume_label: "High" for quantities at least 20 and "Regular" otherwise. Display the first eight rows with these new columns.

In [21]:
df["revenue_amd"] = df["units_sold"] * df["unit_price_amd"]
df["product_label"] = df["category"] + " - " + df["product"]
df["product_name_length"] = df["product"].apply(lambda name: len(name))
df["volume_label"] = np.where(df["units_sold"] >= 20, "High", "Regular")
df.head(8)

,sale_id,day,product,category,units_sold,unit_price_amd,revenue_amd,product_label,product_name_length,volume_label
0,101,1,Notebook,Paper,12,1200,14400,Paper - Notebook,8,Regular
1,102,1,Pen,Writing,30,200,6000,Writing - Pen,3,High
2,103,1,Folder,Paper,8,500,4000,Paper - Folder,6,Regular
3,104,1,Marker,Writing,10,700,7000,Writing - Marker,6,Regular
4,105,2,Notebook,Paper,15,1200,18000,Paper - Notebook,8,Regular
5,106,2,Pen,Writing,24,200,4800,Writing - Pen,3,High
6,107,2,Folder,Paper,6,500,3000,Paper - Folder,6,Regular
7,108,2,Marker,Writing,12,700,8400,Writing - Marker,6,Regular

### 2.3 Select and drop columns — 6 points
Display only day, product, units_sold, and revenue_amd. Create a separate DataFrame called report_df by dropping product_label and product_name_length from df. Display the columns of both DataFrames to demonstrate that those columns still exist in df.

In [22]:
df[["day", "product", "units_sold", "revenue_amd"]]

    day   product  units_sold  revenue_amd
0     1  Notebook          12        14400
1     1       Pen          30         6000
2     1    Folder           8         4000
3     1    Marker          10         7000
4     2  Notebook          15        18000
5     2       Pen          24         4800
6     2    Folder           6         3000
7     2    Marker          12         8400
8     3  Notebook          10        12000
9     3       Pen          35         7000
10    3    Folder           9         4500
11    3    Marker           8         5600
12    4  Notebook          18        21600
13    4       Pen          28         5600
14    4    Folder           7         3500
15    4    Marker          15        10500
16    5  Notebook          20        24000
17    5       Pen          40         8000
18    5    Folder          12         6000
19    5    Marker          16        11200
20    6  Notebook          16        19200
21    6       Pen          32         6400
22    6    Folder          10         5000
23    6    Marker          14         9800

In [23]:
report_df = df.drop(columns=["product_label", "product_name_length"])
print("report_df columns:", list(report_df.columns))
print("df columns:", list(df.columns))

report_df columns: ['sale_id', 'day', 'product', 'category', 'units_sold', 'unit_price_amd', 'revenue_amd', 'volume_label']
df columns: ['sale_id', 'day', 'product', 'category', 'units_sold', 'unit_price_amd', 'revenue_amd', 'product_label', 'product_name_length', 'volume_label']

### Part 3 — Filter, sort, and work with indexes (20 points)

### 3.1 Filter rows — 8 points
Produce three separate results: (a) Writing items with at least 25 units sold; (b) all rows for Days 2 or 5, using isin; (c) rows where the product is Notebook OR revenue is at least 10,000 AMD. For each result, display day, product, units_sold, and revenue_amd.

In [24]:
df[(df["category"] == "Writing") & (df["units_sold"] >= 25)][["day", "product", "units_sold", "revenue_amd"]]

    day product  units_sold  revenue_amd
1     1     Pen          30         6000
9     3     Pen          35         7000
13    4     Pen          28         5600
17    5     Pen          40         8000
21    6     Pen          32         6400

In [25]:
df[df["day"].isin([2, 5])][["day", "product", "units_sold", "revenue_amd"]]

    day   product  units_sold  revenue_amd
4     2  Notebook          15        18000
5     2       Pen          24         4800
6     2    Folder           6         3000
7     2    Marker          12         8400
16    5  Notebook          20        24000
17    5       Pen          40         8000
18    5    Folder          12         6000
19    5    Marker          16        11200

In [26]:
df[(df["product"] == "Notebook") | (df["revenue_amd"] >= 10000)][["day", "product", "units_sold", "revenue_amd"]]

    day   product  units_sold  revenue_amd
0     1  Notebook          12        14400
4     2  Notebook          15        18000
8     3  Notebook          10        12000
12    4  Notebook          18        21600
15    4    Marker          15        10500
16    5  Notebook          20        24000
19    5    Marker          16        11200
20    6  Notebook          16        19200

### 3.2 Sort and find maximums — 6 points
Sort all rows by revenue from highest to lowest, breaking ties by sale_id ascending, and display the first five. Separately, find every row tied for the highest quantity sold. Keep df in its existing order.

In [27]:
df.sort_values(by=["revenue_amd", "sale_id"], ascending=[False, True]).head(5)

,sale_id,day,product,category,units_sold,unit_price_amd,revenue_amd,product_label,product_name_length,volume_label
16,117,5,Notebook,Paper,20,1200,24000,Paper - Notebook,8,High
12,113,4,Notebook,Paper,18,1200,21600,Paper - Notebook,8,Regular
20,121,6,Notebook,Paper,16,1200,19200,Paper - Notebook,8,Regular
4,105,2,Notebook,Paper,15,1200,18000,Paper - Notebook,8,Regular
0,101,1,Notebook,Paper,12,1200,14400,Paper - Notebook,8,Regular

In [28]:
df[df["units_sold"] == df["units_sold"].max()]

,sale_id,day,product,category,units_sold,unit_price_amd,revenue_amd,product_label,product_name_length,volume_label
17,118,5,Pen,Writing,40,200,8000,Writing - Pen,3,High

### 3.3 Change the index — 6 points
Create indexed_df with sale_id as its index. Display its first five rows. Reset that index so sale_id becomes a regular column again, and display the result. Explain why sale_id is a better unique row identifier than product in this dataset.

In [29]:
indexed_df = df.set_index("sale_id")
indexed_df.head()

,day,product,category,units_sold,unit_price_amd,revenue_amd,product_label,product_name_length,volume_label
sale_id,,,,,,,,,
101,1,Notebook,Paper,12,1200,14400,Paper - Notebook,8,Regular
102,1,Pen,Writing,30,200,6000,Writing - Pen,3,High
103,1,Folder,Paper,8,500,4000,Paper - Folder,6,Regular
104,1,Marker,Writing,10,700,7000,Writing - Marker,6,Regular
105,2,Notebook,Paper,15,1200,18000,Paper - Notebook,8,Regular

In [30]:
reset_df = indexed_df.reset_index()
reset_df.head()

,sale_id,day,product,category,units_sold,unit_price_amd,revenue_amd,product_label,product_name_length,volume_label
0,101,1,Notebook,Paper,12,1200,14400,Paper - Notebook,8,Regular
1,102,1,Pen,Writing,30,200,6000,Writing - Pen,3,High
2,103,1,Folder,Paper,8,500,4000,Paper - Folder,6,Regular
3,104,1,Marker,Writing,10,700,7000,Writing - Marker,6,Regular
4,105,2,Notebook,Paper,15,1200,18000,Paper - Notebook,8,Regular

sale_id is a better unique identifier because each of the 24 rows has a different value (101 to 124), so it points to exactly one sale. product only has 4 distinct values, each repeated on 6 days, so a product name like "Pen" matches 6 different rows and cannot identify a single one.

### Part 4 — Group and compare (15 points)

### 4.1 Product and category summaries — 8 points
Use groupby to calculate total units sold per product, mean quantity per row for each product, and total revenue per category. Sort the category revenue totals from highest to lowest. Label every output clearly.

In [31]:
print("Total units sold per product:")
print(df.groupby("product")["units_sold"].sum())

Total units sold per product:
product
Folder       52
Marker       75
Notebook     91
Pen         189
Name: units_sold, dtype: int64

In [32]:
print("Mean quantity per row for each product:")
print(df.groupby("product")["units_sold"].mean())

Mean quantity per row for each product:
product
Folder       8.666667
Marker      12.500000
Notebook    15.166667
Pen         31.500000
Name: units_sold, dtype: float64

In [33]:
print("Total revenue per category (highest to lowest):")
print(df.groupby("category")["revenue_amd"].sum().sort_values(ascending=False))

Total revenue per category (highest to lowest):
category
Paper      135200
Writing     90300
Name: revenue_amd, dtype: int64

### 4.2 Daily totals and a cross-check — 7 points
Calculate total revenue for each day. Identify every day tied for the highest revenue. Then calculate total units per day with pandas and compare those totals with your NumPy totals from Question 1.4, in Day 1–6 order. Display both results and whether they match.

In [34]:
daily_revenue = df.groupby("day")["revenue_amd"].sum()
print("Total revenue per day:")
print(daily_revenue)

Total revenue per day:
day
1    31400
2    34200
3    29100
4    41200
5    49200
6    40400
Name: revenue_amd, dtype: int64

In [35]:
top_days = daily_revenue[daily_revenue == daily_revenue.max()]
print("Day tied for the highest revenue:")
print(top_days)

Day tied for the highest revenue:
day
5    49200
Name: revenue_amd, dtype: int64

In [36]:
pandas_units = df.groupby("day")["units_sold"].sum()
numpy_units = np.sum(units, axis=1)

print("Pandas totals (Day 1 to 6):", pandas_units.values)
print("NumPy totals (Day 1 to 6): ", numpy_units)
print("Do they match?", np.array_equal(pandas_units.values, numpy_units))

Pandas totals (Day 1 to 6): [60 57 62 68 88 72]
NumPy totals (Day 1 to 6):  [60 57 62 68 88 72]
Do they match? True

### Part 5 — Interpret and submit (10 points)

### 5.1 Findings — 6 points
Write three short findings supported by your computed numbers: which product sold the most units; which category generated the most revenue; and which day generated the most revenue. Include any ties. Add one limitation of drawing conclusions about future sales from these six days.

The product with the most units sold is “Pen” with 189 units in 6 days.

Category with the most revenue: Paper, with 135,200 AMD

Day with the most revenue: Day 5, with 49,200 AMD

Limitation: six days is a very small sample, and we know nothing about what drove these sales (weekday vs. weekend, promotions, seasonality, stock availability). A single unusual day, like Day 5, strongly affects the totals, so these results cannot reliably predict future sales.